#ifndef TEXTURES_H_INCLUDED
#define TEXTURES_H_INCLUDED

typedef enum GB_GFX_TEXTURE {
    GFX_TEXTURE_SHIP,
    GFX_TEXTURE_DYNAMIC_FIRST,
    GFX_TEXTURE_DYNAMIC_LAST,
    GFX_TEXTURE_NUM_TEXTURES
} GB_GFX_TEXTURE;

#endif // TEXTURES_H_INCLUDED
