#ifndef GB_FILE_CHUNK_SIZE_H_INCLUDED
#define GB_FILE_CHUNK_SIZE_H_INCLUDED

typedef enum {
    GB_FILE_CHUNK_SIZE_8,
    GB_FILE_CHUNK_SIZE_16,
    GB_FILE_CHUNK_SIZE_32,
    GB_FILE_CHUNK_SIZE_64
} GB_FILE_CHUNK_SIZE;

#endif // GB_FILE_CHUNK_SIZE_H_INCLUDED
