#ifndef GB_GFX_LAYER_H_INCLUDED
#define GB_GFX_LAYER_H_INCLUDED

typedef enum {
    GB_SPRITE_LAYER_BACKGROUND,
    GB_SPRITE_LAYER_MIDGROUND,
    GB_SPRITE_LAYER_FOREGROUND,
    GB_SPRITE_LAYER_NUM_LAYERS
} GB_SPRITE_LAYER;

#endif // GB_GFX_LAYER_H_INCLUDED
