#ifndef GB_ENTITY_PRIORITY_H_INCLUDED
#define GB_ENTITY_PRIORITY_H_INCLUDED

typedef enum {
    GB_ENTITY_PRIORITY_HIGH,
    GB_ENTITY_PRIORITY_MID,
    GB_ENTITY_PRIORITY_LOW,
    GB_ENTITY_PRIORITY_NUM_PRIORITIES
} GB_ENTITY_PRIORITY;

#endif //GB_ENTITY_PRIORITY_H_INCLUDED
