#ifndef GB_ENTITY_TYPE_TYPE_H_INCLUDED
#define GB_ENTITY_TYPE_TYPE_H_INCLUDED

typedef enum {
    GB_ENTITY_TYPE_DINO,
    GB_ENTITY_TYPE_NUM_ENTITY_TYPES
} GB_ENTITY_TYPE;

#endif // GB_ENTITY_TYPE_TYPE_H_INCLUDED
