#ifndef SPRITE_LAYER_H_INCLUDED
#define SPRITE_LAYER_H_INCLUDED

typedef enum {
    SPRITE_LAYER_BACKGROUND,
    SPRITE_LAYER_MIDGROUND,
    SPRITE_LAYER_FOREGROUND,
    SPRITE_LAYER_NUM_LAYERS
} SPRITE_LAYER;

#endif // SPRITE_LAYER_H_INCLUDED
