#ifndef GB_GFX_LAYER_H_INCLUDED
#define GB_GFX_LAYER_H_INCLUDED

typedef enum {
    GB_GFX_LAYER_BACKGROUND,
    GB_GFX_LAYER_MIDGROUND,
    GB_GFX_LAYER_FOREGROUND,
    GB_GFX_LAYER_NUM_LAYERS
} GB_GFX_LAYER;

#endif // GB_GFX_LAYER_H_INCLUDED
