#ifndef GB_TEXTURE_NAMES_H_INCLUDED
#define GB_TEXTURE_NAMES_H_INCLUDED

typedef enum {
    GB_TEXTURE_NAME_OVERLAY,
    GB_TEXTURE_NAME_GUY,
    GB_TEXTURE_NAME_MOVE_ROOM_PANEL,
    GB_TEXTURE_NAME_ENTITY_PALETTE,
    GB_TEXTURE_NAME_POWER_GRID_PALETTE,
    GB_TEXTURE_NAME_CABELS,
    GB_TEXTURE_NAME_SWITCH,
    GB_TEXTURE_NAME_NUM_NAMES
} GB_TEXTURE_NAME;

#endif // GB_TEXTURE_NAMES_H_INCLUDED
