#ifndef ROOM_DIRECTION_ENUM_H_INCLUDED
#define ROOM_DIRECTION_ENUM_H_INCLUDED

typedef enum {
    ROOM_NORTH,
    ROOM_EAST,
    ROOM_SOUTH
    ROOM_WEST,
    ROOM_DIRECTION_COUNT
} RoomDirection;

#endif // ROOM_DIRECTION_ENUM_H_INCLUDED
