#ifndef DYNAMIC_ENTITY_TYPE_H_INCLUDED
#define DYNAMIC_ENTITY_TYPE_H_INCLUDED

typedef enum {
    DYNAMIC_ENTITY_TYPE_GUY,
    DYNAMIC_ENTITY_TYPE_NUM_ENTITY_TYPES
} DYNAMIC_ENTITY_TYPE;

#endif // DYNAMIC_ENTITY_TYPE_H_INCLUDED
